ALTER TABLE campo ADD CONSTRAINT cf1 PRIMARY KEY(id);
ALTER TABLE partido ADD CONSTRAINT cf10 PRIMARY KEY(id_partido);
ALTER TABLE jornada ADD CONSTRAINT cf2 PRIMARY KEY(id_jornada);
ALTER TABLE jugador ADD CONSTRAINT cf3 PRIMARY KEY(id_jugador);
ALTER TABLE arbitro ADD CONSTRAINT cf4 PRIMARY KEY(id_arbitro);
ALTER TABLE equipo ADD CONSTRAINT cf5 PRIMARY KEY(nom_equipo);
ALTER TABLE falta ADD CONSTRAINT cf6 PRIMARY KEY(id_falta);
ALTER TABLE equipo_patrocinador ADD CONSTRAINT cf7 PRIMARY KEY(patrocinador);
ALTER TABLE partido ADD CONSTRAINT cf8 FOREIGN KEY(id_jornada) REFERENCES jornada (id_jornada);
ALTER TABLE partido ADD CONSTRAINT cf9 FOREIGN KEY(id_campo) REFERENCES campo (id);
ALTER TABLE arbitro ADD CONSTRAINT cf11 FOREIGN KEY(id_entrenador) REFERENCES arbitro (id_arbitro);
ALTER TABLE jugador ADD CONSTRAINT cf12 FOREIGN KEY(nom_equipo) REFERENCES equipo (nom_equipo);
ALTER TABLE equipo ADD CONSTRAINT cf13 FOREIGN KEY(id_jcapitan) REFERENCES jugador (id_jugador);
ALTER TABLE equipo_patrocinador ADD CONSTRAINT cf14 FOREIGN KEY(nom_equipo) REFERENCES equipo (nom_equipo);
ALTER TABLE resultado_partido ADD CONSTRAINT cf15 FOREIGN KEY(id_partido) REFERENCES partido (id_partido);
ALTER TABLE resultado_partido ADD CONSTRAINT cf16 FOREIGN KEY(nom_equipo) REFERENCES equipo (nom_equipo);
ALTER TABLE falta ADD CONSTRAINT cf17 FOREIGN KEY(id_partido) REFERENCES partido (id_partido);
ALTER TABLE falta ADD CONSTRAINT cf18 FOREIGN KEY(id_jugador) REFERENCES jugador (id_jugador);
ALTER TABLE arbitro_asignado ADD CONSTRAINT cf19 FOREIGN KEY(id_partido) REFERENCES partido (id_partido);
ALTER TABLE arbitro_asignado ADD CONSTRAINT cf20 FOREIGN KEY(id_arbitro) REFERENCES arbitro (id_arbitro);
ALTER TABLE jugador ADD CONSTRAINT cf21 CHECK (fecha_nac BETWEEN '05/12/99' and '04/12/2001');
ALTER TABLE jugador_partido ADD CONSTRAINT cf22 FOREIGN KEY(id_partido) REFERENCES partido (id_partido);
ALTER TABLE jugador_partido ADD CONSTRAINT cf23 FOREIGN KEY(id_jugador) REFERENCES jugador (id_jugador);
